# Guarneri-style device YAML configuration

id6_b.devices.monochromator.MonoDevice:
- name: mono
  prefix: "6ida1:"
  labels: ["mono", "energy device", "baseline"]

id6_b.devices.energy_device.EnergySignal:
- name: energy
  mono_name: "mono"
  labels: ["energy device", "baseline"]

id6_b.devices.aps_undulator.PolarUndulatorPair:
- name: undulators
  prefix: "S06ID:"
  labels: ["source", "energy device", "baseline"]

id6_b.devices.aps_status.StatusAPS:
- name: status_aps
  prefix: ""
  labels: ["source", "status", "baseline"]

apstools.devices.mb_creator:
- name: crl
  prefix: "6idbSoft:TRANS:"
  motors: 
    ytrans: "m1"
    xtrans: "m2"
    ztrans: "m5"
    yaw: "m3"
    pitch: "m4"
    lens1: "m6"
    lens2: "m7"
    lens3: "m8"
    lens4: "m9"
    lens5: "m10"
    lens6: "m11"
    lens7: "m12"
    lens8: "m13"
    lens9: "m14"
    lens10: "m15"
- name: mirror1
  motors:
    angle:
      factory:
        function: "id6_b.devices.pv_positioner.pvpositioner_factory"
        readback_pv: "6idaSoft:M1yt2.C"
        setpoint_pv: "6idaSoft:M1yangl"
        done_pv: "6idaSoft:M1yDMOV"
        done_value: 1
        stop_pv: "6idaSoft:allstop"
        stop_value: 1
    y_avg:
      factory:
        function: "id6_b.devices.pv_positioner.pvpositioner_factory"
        readback_pv: "6idaSoft:M1yt2.D"
        setpoint_pv: "6idaSoft:M1yavg"
        done_pv: "6idaSoft:M1yDMOV"
        done_value: 1
        stop_pv: "6idaSoft:allstop"
        stop_value: 1
    y_down:
      factory:
        function: "id6_b.devices.pv_positioner.pvpositioner_factory"
        readback_pv: "6idaSoft:M1yt2.A"
        setpoint_pv: "6idaSoft:M1ydn"
        done_pv: "6idaSoft:M1yDMOV"
        done_value: 1
        stop_pv: "6idaSoft:allstop"
        stop_value: 1
    y_up:
      factory:
        function: "id6_b.devices.pv_positioner.pvpositioner_factory"
        readback_pv: "6idaSoft:M1yt2.B"
        setpoint_pv: "6idaSoft:M1yup"
        done_pv: "6idaSoft:M1yDMOV"
        done_value: 1
        stop_pv: "6idaSoft:allstop"
        stop_value: 1


id6_b.devices.scaler.LocalScalerCH:
- name: scaler
  prefix: "6idb1:scaler1"
  labels: ["scaler", "detectors", "baseline"]

apsbits.utils.sim_creator.predefined_device:
- { creator: ophyd.sim.motor, name: sim_motor }
- { creator: ophyd.sim.noisy_det, name: sim_det }

apstools.devices.SimulatedApsPssShutterWithStatus:
- name: shutter
  labels: [ "shutters", "baseline" ]

hklpy2.creator:
- name: psic_sim
  geometry: E6C
  labels: [ "diffractometer", "hklpy2" ]
  reals: [ "mu", "eta", "chi", "phi", "nu", "delta" ]  # simulator
- name: psic
  geometry: E6C
  labels: [ "diffractometer", "hklpy2" ]
  prefix: "6idb1:"  
  reals:
    # MUST provide in canonical order
    # No defined motor assignments, pick different than fourc (m29-32)
    mu: m28
    eta: m17
    chi: m19
    phi: m20
    nu: m29
    delta: m18
- name: psic_psi
  geometry: E6C
  solver_kwargs: {"engine": "psi"}
  labels: [ "diffractometer", "hklpy2" ]
  prefix: "6idb1:"  
  reals:
    mu: m28
    eta: m17
    chi: m19
    phi: m20
    nu: m29
    delta: m18
- name: psic_q
  geometry: E6C
  solver_kwargs: {"engine": "q2"}
  labels: [ "diffractometer", "hklpy2" ]
  prefix: "6idb1:"  
  reals:
    mu: m28
    eta: m17
    chi: m19
    phi: m20
    nu: m29
    delta: m18

# TODO: Lakeshore, SRS570, Keithley DMM, Keithley source meter, capacitance bridge 2700
# https://bcda-aps.github.io/apstools/latest/api/_devices.html#devices-other-support
# BPM: https://github.com/BCDA-APS/8id-bits/blob/4b573f0ae35f6dc5982ff5700221dd704f66d269/src/id8_i/devices/sydor_tp4u.py#L16
# lockin amp: https://github.com/APS-4ID-POLAR/polar_instrument/blob/80c0c3abbd676a00a489ff2a995f1befb7e4856c/src/instrument/devices/4idd/srs810.py#L43

## THIS ARE EXAMPLES OF OTHER DEVICES THAT YOU CAN USE
# ophyd.Signal:
# - name: test
#   value: 50.7
# - name: t2
#   value: 2

# apstools.synApps.Optics2Slit2D_HV:
# - name: slit1
#   prefix: ioc:Slit1
#   labels: ["slits", "baseline"]

# ophyd.scaler.ScalerCH:
# - name: scaler1
#   prefix: vme:scaler1
#   labels: ["scalers", "detectors"]

# ophyd.EpicsMotor:
# - {name: m1, prefix: gp:m1, labels: ["motor"]}
# - {name: m2, prefix: gp:m2, labels: ["motor"]}
# - {name: m3, prefix: gp:m3, labels: ["motor"]}
# - {name: m4, prefix: gp:m4, labels: ["motor"]}

# FIXME: control object fails to load properly
# TODO: after BITS version is upgraded (includes startup.py updates)
#id6_b.devices.lakeshore_controllers.LS340Device:
#- name: lakeshore340
#  # Lakeshore 340 - Low temperature
#  prefix: "6idb1:LS340:TC1:"
#  labels: ["lakeshore", "baseline"]

# id6_b.devices.lambda_detector.Lambda250kDetector:
# - name: lambda250k
#   prefix: "s6lambda1:"
#   labels: ["area_detector", "detectors"]

# apstools.devices.ad_creator:
#   - name: adsimdet
#     prefix: "ad:"
#     labels: ["area_detector", "detectors"]
#     plugins:
#       - cam:
#           class: apstools.devices.SimDetectorCam_V34
#       - image
#       - pva
#       - hdf1:
#           class: apstools.devices.AD_EpicsFileNameHDF5Plugin
#           read_path_template: "/path/to/bluesky/tmp/"
#           write_path_template: "/path/to/ioc/tmp/"
#       - roi1
#       - stats1

# polar_common.devices.srs810.LockinDevice:
# - name: lockin
#   prefix: '4idd:SRS810:1:'
#   labels: [ "detectors", "baseline" ]

# apstools.devices.motor_factory.mb_creator:
#   - name: bundle
#     prefix: "gp:"
#     class_name: MotorBundle
#     motors:
#         x: "m1"
#         y: "m2"
#         z: "m3"
#         alpha: None
#         bravo: None
#         charlie: None
#   - name: sample_stage
#     class_name: SampleStage
#     motors:
#         x: "IOC:m25"
#         y: None
#         theta: None
