#hklpy2 configuration file

_header:
  datetime: '2026-09-04 16:55:27.788579'
  hklpy2_version: 0.7.1
  python_class: Hklpy2Diffractometer
  config_schema_version: 2
  file: /home/beams18/USER6IDB/6idb-bits/psic_6idb_config.yml
  comment: 6-ID-B beamline
name: psic
axes:
  pseudo_axes:
  - h
  - k
  - l
  real_axes:
  - mu
  - eta
  - chi
  - phi
  - nu
  - delta
  axes_xref:
    h: h
    k: k
    l: l
    mu: mu
    eta: omega
    chi: chi
    phi: phi
    nu: gamma
    delta: delta
  extra_axes:
    h2: 1.0
    k2: 0.0
    l2: 0.0
    psi: 0
  auxiliary_axes: []
digits: 4
sample_name: LSAT
samples:
  sample:
    name: sample
    lattice:
      a: 1
      b: 1
      c: 1
      alpha: 90.0
      beta: 90.0
      gamma: 90.0
      digits: 4
      angle_units: degrees
      length_units: angstrom
    reflections: {}
    reflections_order: []
    U:
    - - 1
      - 0
      - 0
    - - 0
      - 1
      - 0
    - - 0
      - 0
      - 1
    UB:
    - - 6.283185307179586
      - 0.0
      - 0.0
    - - 0.0
      - 6.283185307179586
      - 0.0
    - - 0.0
      - 0.0
      - 6.283185307179586
    digits: 4
  STO113:
    name: STO113
    lattice:
      a: 3.905
      b: 3.905
      c: 3.905
      alpha: 90.0
      beta: 90.0
      gamma: 90.0
      digits: 4
      angle_units: degrees
      length_units: angstrom
    reflections:
      940c774:
        name: 940c774
        geometry: E6C
        pseudos:
          h: 0.0
          k: 0.0
          l: 1.0
        reals:
          mu: 0.0
          eta: 11.8461
          chi: 89.9999
          phi: 0.0
          nu: 0.0
          delta: 23.8921
        reals_units: angstrom
        wavelength: 1.239841842592066
        wavelength_units: angstrom
        digits: 4
      fa71a32:
        name: fa71a32
        geometry: E6C
        pseudos:
          h: 1.0
          k: 0.0
          l: 0.0
        reals:
          mu: 0.0
          eta: 11.8461
          chi: 180.0
          phi: 0.0
          nu: 0.0
          delta: 23.8921
        reals_units: angstrom
        wavelength: 1.239841842592066
        wavelength_units: angstrom
        digits: 4
    reflections_order:
    - 940c774
    - fa71a32
    U:
    - - -0.001744453439
      - -0.999996956874
      - -0.001744455703
    - - -1.2978e-06
      - -0.001744456093
      - 0.999998478434
    - - -0.999998478439
      - 0.001744453048
      - 1.745327e-06
    UB:
    - - -0.002806843589
      - -1.609005425519
      - -0.002806847232
    - - -2.088173e-06
      - -0.00280684786
      - 1.609007873726
    - - -1.609007873734
      - 0.002806842961
      - 2.808249e-06
    digits: 4
  LSAT:
    name: LSAT
    lattice:
      a: 3.868
      b: 3.868
      c: 3.868
      alpha: 90.0
      beta: 90.0
      gamma: 90.0
      digits: 4
      angle_units: degrees
      length_units: angstrom
    reflections:
      d79693a:
        name: d79693a
        geometry: E6C
        pseudos:
          h: 0.0
          k: 0.0
          l: 1.0
        reals:
          mu: 0.0
          eta: 11.8461
          chi: 89.9999
          phi: 0.0
          nu: 0.0
          delta: 23.8921
        reals_units: angstrom
        wavelength: 1.239841842592066
        wavelength_units: angstrom
        digits: 4
      1099a69:
        name: 1099a69
        geometry: E6C
        pseudos:
          h: 0.0
          k: 1.0
          l: 0.0
        reals:
          mu: 0.0
          eta: 11.8461
          chi: 180.0
          phi: 0.0
          nu: 0.0
          delta: 23.8921
        reals_units: angstrom
        wavelength: 1.239841842592066
        wavelength_units: angstrom
        digits: 4
    reflections_order:
    - d79693a
    - 1099a69
    U:
    - - 0.999996956874
      - -0.001744453439
      - -0.001744455703
    - - 0.001744456093
      - -1.2978e-06
      - 0.999998478434
    - - -0.001744453048
      - -0.999998478439
      - 1.745327e-06
    UB:
    - - 1.624396635639
      - -0.00283369292
      - -0.002833696598
    - - 0.002833697232
      - -2.108148e-06
      - 1.624399107265
    - - -0.002833692286
      - -1.624399107273
      - 2.835111e-06
    digits: 4
constraints:
  mu:
    label: mu
    low_limit: -180.0
    high_limit: 180.0
    cut_point: -180.0
    class: LimitsConstraint
  eta:
    label: eta
    low_limit: -180.0
    high_limit: 180.0
    cut_point: -180.0
    class: LimitsConstraint
  chi:
    label: chi
    low_limit: -180.0
    high_limit: 180.0
    cut_point: -180.0
    class: LimitsConstraint
  phi:
    label: phi
    low_limit: -180.0
    high_limit: 180.0
    cut_point: -180.0
    class: LimitsConstraint
  nu:
    label: nu
    low_limit: -180.0
    high_limit: 180.0
    cut_point: -180.0
    class: LimitsConstraint
  delta:
    label: delta
    low_limit: -180.0
    high_limit: 180.0
    cut_point: -180.0
    class: LimitsConstraint
solver:
  name: hkl_soleil
  description: HklSolver(name='hkl_soleil', version='5.1.3', geometry='E6C', engine_name='hkl',
    mode='constant_omega_vertical')
  geometry: E6C
  real_axes:
  - mu
  - omega
  - chi
  - phi
  - gamma
  - delta
  version: 5.1.3
  engine: hkl
  mode: constant_omega_vertical
beam:
  class: EpicsMonochromatorRO
  source_type: Synchrotron X-ray Source
  energy: 10.00000481842049
  wavelength: 1.239841842592066
  energy_units: keV
  wavelength_units: angstrom
  wavelength_PV: 6ida1:BraggLambdaRdbkAO
  energy_PV: 6ida1:BraggERdbkAO
presets:
  bissector_vertical: {}
  constant_omega_vertical:
    nu: 0.0
